// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AsideBar': typeof import("../components/AsideBar.vue")['default'],
    'BaseAvatar': typeof import("../components/Base/Avatar.vue")['default'],
    'BaseButton': typeof import("../components/Base/Button.vue")['default'],
    'BaseCard': typeof import("../components/Base/Card.vue")['default'],
    'BaseFormInput': typeof import("../components/Base/Form/Input.vue")['default'],
    'PageHeader': typeof import("../components/PageHeader.vue")['default'],
    'PlaceHolder': typeof import("../components/PlaceHolder.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyAsideBar': typeof import("../components/AsideBar.vue")['default'],
    'LazyBaseAvatar': typeof import("../components/Base/Avatar.vue")['default'],
    'LazyBaseButton': typeof import("../components/Base/Button.vue")['default'],
    'LazyBaseCard': typeof import("../components/Base/Card.vue")['default'],
    'LazyBaseFormInput': typeof import("../components/Base/Form/Input.vue")['default'],
    'LazyPageHeader': typeof import("../components/PageHeader.vue")['default'],
    'LazyPlaceHolder': typeof import("../components/PlaceHolder.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}

export const AsideBar: typeof import("../components/AsideBar.vue")['default'],
export const BaseAvatar: typeof import("../components/Base/Avatar.vue")['default'],
export const BaseButton: typeof import("../components/Base/Button.vue")['default'],
export const BaseCard: typeof import("../components/Base/Card.vue")['default'],
export const BaseFormInput: typeof import("../components/Base/Form/Input.vue")['default'],
export const PageHeader: typeof import("../components/PageHeader.vue")['default'],
export const PlaceHolder: typeof import("../components/PlaceHolder.vue")['default'],
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyAsideBar: typeof import("../components/AsideBar.vue")['default'],
export const LazyBaseAvatar: typeof import("../components/Base/Avatar.vue")['default'],
export const LazyBaseButton: typeof import("../components/Base/Button.vue")['default'],
export const LazyBaseCard: typeof import("../components/Base/Card.vue")['default'],
export const LazyBaseFormInput: typeof import("../components/Base/Form/Input.vue")['default'],
export const LazyPageHeader: typeof import("../components/PageHeader.vue")['default'],
export const LazyPlaceHolder: typeof import("../components/PlaceHolder.vue")['default'],
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']

export const componentNames: string[]
